### PR TITLE
Add auth/verify function to activate blade file

### PR DESCRIPTION
**Pull request by kofimokome**
I placed the routes I used in `views/backend/activate/route.txt` in order to avoid merge conflicts
kindly copy them to web.php after merge

### CODE REVIEW

**Comment by kofimokome** [comment]
creating db seed for otp will push soon

**Comment by kofimokome** [comment]
seeder added

**Comment by goodhands** [comment]
Please copy them yourself, there will surely be merge conflicts.

Also please state what your PR does, if possible add a screenshot of the page you worked on.

👍

**Comment by kofimokome** [comment]
@goodhands ,
This PR gets the opt token sent to a user's email or phone number and validate if It is correct on the database, then it sets the user's is_active field to 1 and redirects the user to the dashboard.

Screen Shot 2020-06-29 at 08 46 04
Screen Shot 2020-06-29 at 08 46 35
Screen Shot 2020-06-29 at 08 46 19

**Pull request closed without merging**
